services:
  - type: web
    name: music-app-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
